name 'win_workstation'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures win_workstation'
long_description 'Installs/Configures win_workstation'
version '0.1.0'
