---
provisioner:
  name: dsc
  dsc_local_configuration_manager_version: wmf5
  dsc_local_configuration_manager:
    reboot_if_needed: true

driver:
  name: vagrant
  vm_hostname: false # do not bother trying to change the hostname (sometimes fails)
  communicator: winrm
  linked_clones: true
  gui: false
  customize:
    cpus: 2
    memory: 2048

transport:
  name: winrm

verifier:
  name: inspec

platforms:
  - name: windows_2012r2
    driver:
      box: mwrock/Windows2012R2

suites:
  - name: create_DomainController
